Building DAG of jobs...
Traceback (most recent call last):
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 1559, in collect_potential_dependencies
    yield PotentialDependency(file, known_producers[file], True)
KeyError: '/data/exploratory/Users/jasmine.alvarez/orpheus/outs/kallisto-test-20210811/trimmed/reads_1.fq.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 97, in new
    obj = self.cache[key]
KeyError: ('trimmomatic_pe', ('ID', 'kallisto-test-20210811'), ('outpath', '/data/exploratory/Users/jasmine.alvarez/orpheus/outs'), ('sample', 'reads'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 695, in snakemake
    success = workflow.execute(
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 713, in execute
    dag.init()
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 178, in init
    job = self.update([job], progress=progress, create_inventory=True)
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 736, in update
    self.update_(
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 825, in update_
    for res in potential_dependencies:
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 1569, in collect_potential_dependencies
    yield PotentialDependency(file, file2jobs(file), False)
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 1654, in file2jobs
    jobs.append(self.new_job(rule, targetfile=targetfile))
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 1393, in new_job
    job = self.job_factory.new(
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 99, in new
    obj = Job(rule, dag, wildcards_dict, format_wildcards, targetfile)
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 158, in __init__
    self.input, input_mapping, self.dependencies = self.rule.expand_input(
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/rules.py", line 802, in expand_input
    self._apply_wildcards(
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/rules.py", line 725, in _apply_wildcards
    item = self.apply_path_modifier(item, property=property)
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/rules.py", line 447, in apply_path_modifier
    return {k: apply(v) for k, v in item.items()}
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/rules.py", line 447, in <dictcomp>
    return {k: apply(v) for k, v in item.items()}
  File "/data/sw/Anaconda/3.8/envs/snakemake/lib/python3.9/site-packages/snakemake/path_modifier.py", line 32, in modify
    modified_path.flags.update(path.flags)
AttributeError: 'Flags' object has no attribute 'update'
